import os

#####################################
#####   Projeto Pizzaria - V3   #####
#####################################

op_prin = ''
while op_prin != '0':
    os.system('clear')
    print('----------------------------------------------')
    print('|         Sistema de Gestão - Pizzaria       |')
    print('----------------------------------------------')
    print('|             1 - Clientes                   |')
    print('|             2 - Menu                       |')
    print('|             3 - Pedidos                    |')
    print('|             4 - Funcionários               |')
    print('|             5 - Administração              |')
    print('|             6 - Sobre a Pizzaria           |')
    print('|             0 - Sair                       |')
    print('----------------------------------------------')
    op_prin = input("Escolha sua opção: ")
    
    if op_prin == '1':
        op_cliente = ''
        while op_cliente !='0':
            os.system('clear')
            print()
            print('----------------------------------------------')
            print('|                   Clientes                 |')
            print('----------------------------------------------')
            print('|             1 - Cadastre - se              |')
            print('|             2 - Exibir Dados               |')
            print('|             3 - Alterar Dados              |')
            print('|             4 - Excluir Cliente            |')
            print('|             4 - Histórico de Pedidos       |')
            print('|             0 - Retornar ao Menu Principal |')
            print('----------------------------------------------')
            print()
            op_cliente = input("Escolha sua opção: ")
            print()
            if op_cliente == '1':
                os.system('clear')
                print()
                print('----------------------------------------------')
                print('|                  Cadastre - se             |')
                print('----------------------------------------------')
                print('| Nome   | Telefone   | Email   | Endereço   |')
                print('----------------------------------------------')
                print()
                nome = input('Nome: ')
                print()
                fone = input('Telefone: ')
                print()
                email = input('Email: ')
                print()
                endereco = input('Endereço: ')
                print()
                print('Cadatro feito com sucesso!!')
                input('Tecle <ENTER> para combinar...')
            elif op_cliente == '2':
                os.system('clear')
                print()
                print('----------------------------------------------')
                print('|                  Exibir Dados              |')
                print('----------------------------------------------')
                print('| Nome   | Telefone   | Email   | Endereço   |')
                print('----------------------------------------------')
                print()
                print('Nome: ')
                print('Telefone: ')
                print('Email: ')
                print('Endereço: ')
                print()
                input('Tecle <ENTER> para combinar...')
            elif op_cliente == '3':
                os.system('clear')
                print()
                print('----------------------------------------------')
                print('|                  Alterar Dados             |')
                print('----------------------------------------------')
                print('| Nome   | Telefone   | Email   | Endereço   |')
                print('----------------------------------------------')
                print()
                nome = input('Nome: ')
                print()
                fone = input('Telefone: ')
                print()
                email = input('Email: ')
                print()
                endereco = input('Endereço: ')
                print()
                print('Dados alterados com sucesso!!')
                input('Tecle <ENTER> para combinar...')
            elif op_cliente == '4':
                os.system('clear')
                print('----------------------------------------------')
                print('|                Excluir Cliente             |')
                print('----------------------------------------------')
                email = input('Email: ')
                print()
                print('Cliente excluido com sucesso!!')
                input('Tecle <ENTER> para combinar...')
    elif op_prin == '2':
        print()
        print('----------------------------------------------')
        print('|                Funcionários                |')
        print('----------------------------------------------')
        print('|             1 - Login                      |')
        print('|             2 - Controle de Pedidos        |')
        print('|             3 - Estoque                    |')
        print('|             0 - Retornar ao Menu Principal |')
        print('----------------------------------------------')
        print()
        resp2 = input("Escolha sua opção: ")
        print()
        input("Tecle <ENTER> para continuar...")
    elif op_prin == '3':
        print()
        print('----------------------------------------------')
        print('|                 Administração              |')
        print('----------------------------------------------')
        print('|             1 - Relatório de Vendas        |')
        print('|             2 - Despesas                   |')
        print('|             3 - Gestão Geral               |')
        print('|             0 - Retornar ao Menu Principal |')
        print('----------------------------------------------')
        print()
        resp2 = input("Escolha sua opção: ")
        print()
        input("Tecle <ENTER> para continuar...")
    elif op_prin == '4':
        print()
        print('----------------------------------------------')
        print('|            Sobre a Pizzaria                |')
        print('----------------------------------------------')
        print('| Projeto de Gestão de Pizzaria.             |')
        print('| Desenvolvido por: Paulo Douglas.           |')
        print('| Email: paulo.martins.132@ufrn.edu.com      |')
        print('| GitHub: Paulo-Douglas                      |')
        print('----------------------------------------------')
        input("Tecle <ENTER> para continuar...")

print("Você encerrou o programa!")
print("Até logo!")